FROM node:alpine 
RUN cd /usr && mkdir app

WORKDIR '/usr/app'
# package.json을 먼저 COPY하고 npm install 함으로써 소스 코드 변경시 불필요하게 npm install 안하도록 설정
COPY package*.json ./
RUN npm install
# 소스코드 COPY
COPY ./ ./

CMD [ "npm", "run", "start" ]